### ISSUE TITLE
Baseline tests fail in nextest tree

### ISSUE THREAD

**Issue by sourcefrog** [sourcefrog/cargo-mutants#226]
```
        FAIL [   1.824s] integration-tests::integration test_list_default

--- STDOUT:              integration-tests::integration test_list_default ---

running 1 test
test test_list_default ... FAILED

failures:

failures:
    test_list_default

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 14 filtered out; finished in 1.82s


--- STDERR:              integration-tests::integration test_list_default ---
thread 'test_list_default' panicked at integration-tests/tests/integration/fixtures.rs:201:13:
command failed:

command: "/ram/cargo-mutants-nextest-vxXZEX.tmp/target/debug/cargo-nextest-dup" "nextest" "--manifest-path" "/ram/nextest-fixtureUEjaIQ/src/Cargo.toml" "list" "--workspace" "--all-targets" "--message-format" "json"
exit code: Some(101)
--- stdout ---


--- stderr ---
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
info: experimental features enabled: setup-scripts
warning: /ram/nextest-fixtureUEjaIQ/src/Cargo.toml: only one of `license` or `license-file` is necessary
`license` should be used if the package license can be expressed with a standard SPDX expression.
`license-file` should be used if the package uses a non-standard license.
See https://doc.rust-lang.org/cargo/reference/manifest.html#the-license-and-license-file-fields for more information.
   Compiling uuid v1.2.1
   Compiling dylib-test v0.1.0 (/ram/nextest-fixtureUEjaIQ/src/dylib-test)
   Compiling cdylib-link v0.1.0 (/ram/nextest-fixtureUEjaIQ/src/cdylib/cdylib-link)
   Compiling with-build-script v0.1.0 (/ram/nextest-fixtureUEjaIQ/src/with-build-script)
   Compiling cdylib-example v0.1.0 (/ram/nextest-fixtureUEjaIQ/src/cdylib/cdylib-example)
   Compiling nextest-derive v0.1.0 (/ram/nextest-fixtureUEjaIQ/src/derive)
   Compiling nextest-tests v0.1.0 (/ram/nextest-fixtureUEjaIQ/src)
error: failed to run custom build command for `cdylib-link v0.1.0 (/ram/nextest-fixtureUEjaIQ/src/cdylib/cdylib-link)`

Caused by:
  process didn't exit successfully: `/ram/nextest-fixtureUEjaIQ/src/target/debug/build/cdylib-link-e65970b22ab3b7db/build-script-build` (exit status: 101)
  --- stderr
  warning: /ram/nextest-fixtureUEjaIQ/src/Cargo.toml: only one of `license` or `license-file` is necessary
  `license` should be used if the package license can be expressed with a standard SPDX expression.
  `license-file` should be used if the package uses a non-standard license.
  See https://doc.rust-lang.org/cargo/reference/manifest.html#the-license-and-license-file-fields for more information.
  error: failed to get `uuid` as a dependency of package `nextest-tests v0.1.0 (/ram/nextest-fixtureUEjaIQ/src)`

  Caused by:
    failed to load source for dependency `uuid`

  Caused by:
    Unable to update registry `crates-io`

  Caused by:
    failed to update replaced source registry `crates-io`

  Caused by:
    failed to read root of directory source: /ram/nextest-fixtureUEjaIQ/src/vendor

  Caused by:
    No such file or directory (os error 2)
  thread 'main' panicked at cdylib/cdylib-link/build.rs:23:9:
  cargo build failed with status Some(101)
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: cannot satisfy dependencies so `std` only shows up once
  |
  = help: having upstream crates all available in one format will likely make this go away

error: cannot satisfy dependencies so `core` only shows up once
  |
  = help: having upstream crates all available in one format will likely make this go away

error: cannot satisfy dependencies so `compiler_builtins` only shows up once
  |
  = help: having upstream crates all available in one format will likely make this go away

error: cannot satisfy dependencies so `rustc_std_workspace_core` only shows up once
  |
  = help: having upstream crates all available in one format will likely make this go away

error: cannot satisfy dependencies so `alloc` only shows up once
  |
  = help: having upstream crates all available in one format will likely make this go away

error: cannot satisfy dependencies so `libc` only shows up once
  |
  = help: having upstream crates all available in one format will likely make this go away

error: cannot satisfy dependencies so `unwind` only shows up once
  |
  = help: having upstream crates all available in one format will likely make this go away

error: cannot satisfy dependencies so `cfg_if` only shows up once
  |
  = help: having upstream crates all available in one format will likely make this go away

error: cannot satisfy dependencies so `miniz_oxide` only shows up once
  |
  = help: having upstream crates all available in one format will likely make this go away

error: cannot satisfy dependencies so `adler` only shows up once
  |
  = help: having upstream crates all available in one format will likely make this go away

error: cannot satisfy dependencies so `hashbrown` only shows up once
  |
  = help: having upstream crates all available in one format will likely make this go away

error: cannot satisfy dependencies so `rustc_std_workspace_alloc` only shows up once
  |
  = help: having upstream crates all available in one format will likely make this go away

error: cannot satisfy dependencies so `std_detect` only shows up once
  |
  = help: having upstream crates all available in one format will likely make this go away

error: cannot satisfy dependencies so `rustc_demangle` only shows up once
  |
  = help: having upstream crates all available in one format will likely make this go away

error: cannot satisfy dependencies so `addr2line` only shows up once
  |
  = help: having upstream crates all available in one format will likely make this go away

error: cannot satisfy dependencies so `gimli` only shows up once
  |
  = help: having upstream crates all available in one format will likely make this go away

error: cannot satisfy dependencies so `object` only shows up once
  |
  = help: having upstream crates all available in one format will likely make this go away

error: cannot satisfy dependencies so `memchr` only shows up once
  |
  = help: having upstream crates all available in one format will likely make this go away

error: cannot satisfy dependencies so `panic_unwind` only shows up once
  |
  = help: having upstream crates all available in one format will likely make this go away

error: could not compile `nextest-tests` (lib test) due to 19 previous errors
error: command `/home/mbp/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/cargo test --no-run --message-format json-render-diagnostics --workspace --all-targets` exited with code 101



note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

        PASS [   1.998s] integration-tests::integration test_setup_script_error
------------
     Summary [   2.000s] 27/215 tests run: 6 passed, 21 failed, 0 skipped
        FAIL [   1.769s] integration-tests::integration test_list_binaries_only
        FAIL [   1.824s] integration-tests::integration test_list_default
        FAIL [   1.796s] integration-tests::integration test_list_full
        FAIL [   1.734s] integration-tests::integration test_list_full_after_build
        FAIL [   1.803s] integration-tests::integration test_list_host_after_build
        FAIL [   1.808s] integration-tests::integration test_list_target_after_build
        FAIL [   1.715s] integration-tests::integration test_relocated_run
        FAIL [   1.777s] integration-tests::integration test_run
        FAIL [   1.820s] integration-tests::integration test_run_after_build
        FAIL [   1.741s] integration-tests::integration test_run_from_archive
        FAIL [   1.777s] integration-tests::integration test_show_config_test_groups
        FAIL [   0.064s] integration-tests::integration test_target_dir
        FAIL [   0.080s]    nextest-runner::integration basic::test_filter_expr_with_string_filters
        FAIL [   0.074s]    nextest-runner::integration basic::test_filter_expr_without_string_filters
        FAIL [   0.069s]    nextest-runner::integration basic::test_list_binaries
        FAIL [   0.077s]    nextest-runner::integration basic::test_list_tests
        FAIL [   0.080s]    nextest-runner::integration basic::test_retries::retry_overrides_ignored
        FAIL [   0.073s]    nextest-runner::integration basic::test_retries::retry_overrides_obeyed
        FAIL [   0.073s]    nextest-runner::integration basic::test_run
        FAIL [   0.076s]    nextest-runner::integration basic::test_run_ignored
        FAIL [   0.069s]    nextest-runner::integration basic::test_string_filters_without_filter_expr
error: test run failed

*** result: Failure

  47.417917145s ERROR cargo test failed in an unmutated tree, so no mutants were tested
```

**Comment by sourcefrog** [comment]
The `vendor` bit points to an `.ignore` file so I wonder if this is a bad interaction with gitignore handling...

**Comment by sourcefrog** [comment]
The tests do pass when I run the same command in the tempdir, so it's a bit mysterious!

**Comment by sourcefrog** [comment]
I'm going to unassign and deprioritize this for now because while it _might_ be pointing to a bug in cargo-mutants or a failure to handle some reasonable behavior, it also seems really entangled with some quirks in Nextest.
